# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-github-runners
  description: This component is responsible for provisioning EC2 instances for GitHub runners
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
